# Use "&" to express color codes
message:
  banSuccess: "&a%name%&b was banned successfully"
  unBanSuccess: "&a%name%&b was unbanned successfully"
  isNotBanned: "&a%name%&b is not banned"
  isBanned: "&a%name%&b is banned\n&3reason: &2%reason%\n&3time: &2%time%\n&3source: &2%source%"
  isBannedIp: "&a%name%&b is ip-banned\n&3reason: &2%reason%\n&3time: &2%time%"
  invalidSyntax: "&bThe syntax is invalid"
  invalidPlayerName: "&bThe player name &a%name%&b is invalid"
  ipNotFound: "&bIP address of &a%name%&b is not found"
  noSuchCommand: "&bNo such a command exists"
  configReloaded: "&bThe config was reloaded successfully"
  youAreBanned: "&bYou are banned: &a%reason%"

# This will be used when any reasons are specified.
defaultBanReason: Banned by an operator.

# Installing Floodgate is required for this setting.
# Turn this true, and you can ban a Floodgate player who has never joined a network.
floodgateEnabled: false
